version: '3.8'

services:
  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: always
    env_file: 
      - .env
    environment: 
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  postgres:
    restart: always
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "54032:5432"
    networks:
      - qmeter_network
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  qmeter_web:
    restart: always
    build: ./src
    container_name: qmeter_web
    networks:
      - qmeter_network
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src:/src
      - ./src/core:/src/core
      - ./src/static:/src/static
      - ./src/media:/src/media
    ports:
      - "8004:8000"
    env_file:
      - .env
    depends_on:
      - mongo
      - postgres

volumes:
  mongo_data:
    driver: local
  postgres_data:
    driver: local
    
networks:
  qmeter_network:
    driver: bridge