version: '3.8'

services:
  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: always
    env_file: 
      - .env
    environment: 
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
      - MONGO_INITDB_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_PASSWORD=${MONGO_DB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  postgres:
    restart: always
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "54032:5432"
    networks:
      - qmeter_network
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  qmeter_web:
    restart: always
    build: ./src
    container_name: qmeter_web
    networks:
      - qmeter_network
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 --timeout 300 --worker-class=gevent --worker-connections=1000 --workers=5 core.wsgi"
    volumes:
      - ./src:/src
      - ./src/core:/src/core
      - ./src/static:/src/static
      - ./src/media:/src/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo
      - postgres

  nginx:
    restart: always
    build: ./nginx
    volumes:
      - ./src:/usr/share/nginx/html
    ports:
      # - "443:443"
      - "8080:80"
    depends_on:
      - qmeter_web
    networks:
      - qmeter_network

volumes:
  postgres_data:
    driver: local
  mongo_data:
    driver: local

networks:
  qmeter_network:
    driver: bridge